# Generated by Django 5.0.7 on 2024-07-27 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorAdvertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_title', models.CharField(max_length=255)),
                ('ad_id', models.IntegerField()),
                ('ad_views', models.IntegerField()),
                ('ad_position', models.IntegerField()),
                ('ad_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to='handlerapi.authoradvertisement')),
            ],
        ),
    ]
